shopit/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url
from django.utils.translation import ugettext_lazy as _
from django.views.generic import RedirectView

from shopit import views
from shopit.conf import app_settings


def get_urls(name, prefixed=app_settings.SINGLE_APPHOOK):  # noqa
    """
    Returns url patterns for the given module.
    Checks if urls are handled with single or multiple apphooks.
    """
    pk_regexp = r'(?P<pk>\d+)'
    slug_regexp = r'(?P<slug>[-_\w\d]+)'
    path_regexp = r'(?P<path>[-_/\w\d]+)'
    list_regexp = r'^$'
    detail_regexp = r'^%s/$' % slug_regexp

    if name == 'shop':
        cart_regexp = _(r'cart/$')
        cart_empty_regexp = _(r'cart/empty/$')
        watch_regexp = _(r'watch/$')
        checkout_regexp = _(r'checkout/$')
        thanks_regexp = _(r'thanks/$')

        if prefixed:
            list_regexp = _(r'shop/$')
            cart_regexp = _(r'shop/cart/$')
            cart_empty_regexp = _(r'shop/cart/empty/$')
            watch_regexp = _(r'shop/watch/$')
            checkout_regexp = _(r'shop/checkout/$')
            thanks_regexp = _(r'shop/thanks/$')

        return [
            url(list_regexp, RedirectView.as_view(pattern_name='shopit-cart')),
            url(cart_regexp, views.CartView.as_view(), name='shopit-cart'),
            url(cart_empty_regexp, views.CartView.as_view(empty=True), name='shopit-cart-empty'),
            url(watch_regexp, views.WatchView.as_view(), name='shopit-watch'),
            url(checkout_regexp, views.CheckoutView.as_view(), name='shopit-checkout'),
            url(thanks_regexp, views.ThanksView.as_view(), name='shopit-thanks'),
        ]

    if name == 'account':
        reset_confirm_kwargs = r'(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})'

        detail_regexp = list_regexp
        login_regexp = _(r'^login/$')
        logout_regexp = _(r'^logout/$')
        register_regexp = _(r'^register/$')
        reset_regexp = _(r'^reset/$')
        reset_confirm_regexp = _(r'^reset/confirm/%s/$') % reset_confirm_kwargs
        order_list_regexp = _(r'^orders/$')
        order_detail_regexp = _(r'^orders/%s/$') % pk_regexp
        order_latest_regexp = _(r'^orders/latest/$')
        settings_regexp = _(r'^settings/$')
        settings_details_regexp = _(r'^settings/details/$')
        settings_password_regexp = _(r'^settings/password/$')

        if prefixed:
            detail_regexp = _(r'^account/$')
            login_regexp = _(r'^account/login/$')
            logout_regexp = _(r'^account/logout/$')
            register_regexp = _(r'^account/register/$')
            reset_regexp = _(r'^account/reset/$')
            reset_confirm_regexp = _(r'^account/reset/confirm/%s/$') % reset_confirm_kwargs
            order_list_regexp = _(r'^account/orders/$')
            order_detail_regexp = _(r'^account/orders/%s/$') % pk_regexp
            order_latest_regexp = _(r'^account/orders/latest/$')
            settings_regexp = _(r'^account/settings/$')
            settings_details_regexp = _(r'^account/settings/details/$')
            settings_password_regexp = _(r'^account/settings/password/$')

        return [
            url(detail_regexp, views.AccountDetailView.as_view(), name='shopit-account-detail'),
            url(login_regexp, views.AccountLoginView.as_view(), name='shopit-account-login'),
            url(logout_regexp, views.AccountLogoutView.as_view(), name='shopit-account-logout'),
            url(register_regexp, views.AccountRegisterView.as_view(), name='shopit-account-register'),
            url(reset_regexp, views.AccountResetView.as_view(), name='shopit-account-reset'),
            url(reset_confirm_regexp, views.AccountResetConfirmView.as_view(), name='shopit-account-reset-confirm'),
            url(order_list_regexp, views.AccountOrderView.as_view(), name='shopit-account-order-list'),
            url(order_detail_regexp, views.AccountOrderView.as_view(many=False), name='shopit-account-order-detail'),
            url(order_latest_regexp, views.AccountOrderView.as_view(latest=True), name='shopit-account-order-latest'),
            url(settings_regexp, views.AccountSettingsView.as_view(), name='shopit-account-settings'),
            url(settings_details_regexp, views.AccountSettingsView.as_view(action='details'),
                name='shopit-account-settings-details'),
            url(settings_password_regexp, views.AccountSettingsView.as_view(action='password'),
                name='shopit-account-settings-password'),
        ]

    if name == 'categories':
        detail_regexp = r'^%s/$' % path_regexp

        if prefixed:
            list_regexp = _(r'^categories/$')
            detail_regexp = _(r'^categories/%s/$') % path_regexp

        return [
            url(list_regexp, views.CategoryListView.as_view(), name='shopit-category-list'),
            url(detail_regexp, views.CategoryDetailView.as_view(), name='shopit-category-detail'),
        ]

    if name == 'brands':
        detail_regexp = r'^%s/$' % path_regexp

        if prefixed:
            list_regexp = _(r'^brands/$')
            detail_regexp = _(r'^brands/%s/$') % path_regexp

        return [
            url(list_regexp, views.BrandListView.as_view(), name='shopit-brand-list'),
            url(detail_regexp, views.BrandDetailView.as_view(), name='shopit-brand-detail'),
        ]

    if name == 'manufacturers':
        detail_regexp = r'^%s/$' % path_regexp

        if prefixed:
            list_regexp = _(r'^manufacturers/$')
            detail_regexp = _(r'^manufacturers/%s/$') % path_regexp

        return [
            url(list_regexp, views.ManufacturerListView.as_view(), name='shopit-manufacturer-list'),
            url(detail_regexp, views.ManufacturerDetailView.as_view(), name='shopit-manufacturer-detail'),
        ]

    if name == 'products':
        review_regexp = _(r'^%s/reviews/$') % slug_regexp
        review_detail_regexp = _(r'^%s/reviews/%s/$') % (slug_regexp, pk_regexp)
        add_to_cart_regexp = _(r'^%s/add-to-cart/$') % slug_regexp

        if prefixed:
            list_regexp = _(r'^products/$')
            detail_regexp = _(r'^products/%s/$') % slug_regexp
            review_regexp = _(r'^products/%s/reviews/$') % slug_regexp
            review_detail_regexp = _(r'^products/%s/reviews/%s/$') % (slug_regexp, pk_regexp)
            add_to_cart_regexp = _(r'^products/%s/add-to-cart/$') % slug_regexp

        return [
            url(list_regexp, views.ProductListView.as_view(), name='shopit-product-list'),
            url(detail_regexp, views.ProductDetailView.as_view(), name='shopit-product-detail'),
            url(review_regexp, views.ProductReviewListView.as_view(), name='shopit-product-review-list'),
            url(review_detail_regexp, views.ProductReviewDetailView.as_view(), name='shopit-product-review-detail'),
            url(add_to_cart_regexp, views.AddToCartView.as_view(), name='shopit-add-to-cart'),
        ]


urlpatterns = []
for name in ('shop', 'account', 'categories', 'brands', 'manufacturers', 'products'):
    urlpatterns.extend(get_urls(name, prefixed=True))

shopit/models/product.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

import itertools
from collections import OrderedDict
from datetime import datetime
from decimal import Decimal
from os.path import basename

from cms.models.fields import PlaceholderField
from cms.utils.i18n import get_current_language
from django.conf import settings
from django.core.exceptions import ValidationError
from django.core.urlresolvers import NoReverseMatch, reverse
from django.core.validators import MinValueValidator
from django.db import models, transaction
from django.db.models import Count
from django.db.models.query import QuerySet
from django.template.defaultfilters import truncatewords
from django.utils import timezone
from django.utils.decorators import method_decorator
from django.utils.encoding import python_2_unicode_compatible
from django.utils.functional import cached_property
from django.utils.text import slugify
from django.utils.translation import ugettext_lazy as _
from django_measurement.models import MeasurementField
from easy_thumbnails.exceptions import InvalidImageFormatError
from filer.fields.file import FilerFileField
from measurement.measures import Distance, Mass
from mptt.fields import TreeForeignKey
from parler.managers import TranslatableManager, TranslatableQuerySet
from parler.models import TranslatableModel, TranslatedFields
from parler.utils.context import switch_language
from polymorphic.query import PolymorphicQuerySet
from shop.models.product import BaseProduct, BaseProductManager
from shop.money.fields import MoneyField

from shopit.conf import app_settings
from shopit.models.cart import Cart
from shopit.models.categorization import Brand, Category, Manufacturer
from shopit.models.customer import Customer
from shopit.models.flag import Flag
from shopit.models.modifier import Modifier
from shopit.models.tax import Tax
from shopit.utils import get_error_message as em

try:
    from easy_thumbnails.files import get_thumbnailer
    from easy_thumbnails.alias import aliases
    EASY_THUMBNAILS = True
except ImportError:  # pragma: no cover
    EASY_THUMBNAILS = False


class ProductQuerySet(PolymorphicQuerySet, TranslatableQuerySet):
    def active(self):
        return self.filter(active=True)

    def top_level(self):
        return self.filter(kind__in=[Product.SINGLE, Product.GROUP])

    def filter_categorization(self, categories=None, brands=None, manufacturers=None):
        """
        Filters a queryset by the given categorization. A list of slugs should
        be passed in.
        """
        filters = {}
        if categories:
            ids = Category.objects.translated(slug__in=categories).values_list('id', flat=True)
            filters['_category_id__in'] = list(set(ids))
        if brands:
            ids = Brand.objects.translated(slug__in=brands).values_list('id', flat=True)
            filters['_brand_id__in'] = list(set(ids))
        if manufacturers:
            ids = Manufacturer.objects.translated(slug__in=manufacturers).values_list('id', flat=True)
            filters['_manufacturer_id__in'] = list(set(ids))
        return self.filter(**filters) if filters else self

    def filter_flags(self, flags=None):
        """
        Filters a queryset by the given flags. A list of codes should be
        passed in.
        """
        filters = {}
        if flags:
            flagged = self.prefetch_related('flags').filter(flags__code__in=flags)
            flagged = flagged.annotate(num_flags=Count('flags')).filter(num_flags=len(flags)).distinct()
            filters['id__in'] = flagged.values_list('id', flat=True)
        return self.filter(**filters) if filters else self

    def filter_modifiers(self, modifiers=None):
        """
        Filters a queryset by the given modifiers. A list of codes should be
        passed in.
        """
        filters = {}
        if modifiers:
            enabled = Modifier.objects.filtering_enabled().active().values_list('code', flat=True)
            if len([x for x in modifiers if x in enabled]) < len(modifiers):
                # Return empty queryset if invalid modifiers are passed in.
                return self.none()

            modded = self.prefetch_related('modifiers').filter(modifiers__code__in=modifiers)
            modded = modded.annotate(num_mods=Count('modifiers')).filter(num_mods=len(modifiers)).distinct()
            filters['id__in'] = modded.values_list('id', flat=True)
        return self.filter(**filters) if filters else self

    def filter_attributes(self, attributes=None):
        """
        Filters a queryset by attributes. A list of tuples containing attribute
        code, name should be passed in as `attributes`.
        """
        if attributes:
            ids = self.values_list('id', flat=True)
            variants = Product.objects.filter(group_id__in=ids).\
                prefetch_related('attribute_values', 'attribute_values__attribute', 'attribute_values__choice')

            if variants:
                for code, value in attributes:
                    filters = {'attribute_values__attribute__code__iexact': code}
                    if value:
                        filters['attribute_values__choice__value__iexact'] = value
                    else:
                        filters['attribute_values__choice__isnull'] = True
                    variants = variants.filter(**filters)

                group_ids = list(set(variants.values_list('group_id', flat=True)))
                self = self.filter(id__in=group_ids)

                if app_settings.FILTER_ATTRIBUTES_INCLUDES_VARIANTS:
                    self = (variants | self).order_by('-order', 'kind', 'published')
        return self

    def filter_price(self, price_from=None, price_to=None):
        """
        Filters a queryset by a price range.
        """
        filters = {}
        if price_from:
            filters['_unit_price__gte'] = Decimal(price_from)
        if price_to:
            filters['_unit_price__lte'] = Decimal(price_to)
        return self.filter(**filters) if filters else self


class ProductManager(BaseProductManager, TranslatableManager):
    queryset_class = ProductQuerySet

    def active(self):
        return self.get_queryset().active()

    def top_level(self):
        return self.get_queryset().top_level()

    def filter_categorization(self, categories=None, brands=None, manufacturers=None):
        return self.get_queryset().filter_categorization(categories, brands, manufacturers)

    def filter_flags(self, flags=None):
        return self.get_queryset().filter_flags(flags)

    def filter_modifiers(self, modifiers=None):
        return self.get_queryset().filter_modifiers(modifiers)

    def filter_price(self, price_from=None, price_to=None):
        return self.get_queryset().filter_price(price_from, price_to)

    def filter_attributes(self, attributes=None):
        return self.get_queryset().filter_attributes(attributes)


@python_2_unicode_compatible
class Product(BaseProduct, TranslatableModel):
    """
    Product model.
    """
    SINGLE, GROUP, VARIANT = range(3)

    KINDS = (
        (SINGLE, _('Single')),
        (GROUP, _('Group')),
        (VARIANT, _('Variant')),
    )

    translations = TranslatedFields(
        name=models.CharField(
            _('Name'),
            max_length=128,
        ),
        slug=models.SlugField(
            _('Slug'),
            db_index=True,
            help_text=_("Part that's used in url to display this product. Needs to be unique."),
        ),
        _caption=models.TextField(
            _('Caption'),
            max_length=255,
            blank=True,
            help_text=_("Short product caption, usually used in catalog's list view of products."),
        ),
        _description=models.TextField(
            _('Description'),
            blank=True,
            help_text=_("Description of a product, usually used as lead text in product's detail view."),
        ),
        meta={
            'unique_together': [('language_code', 'slug')],
        },
    )

    code = models.CharField(
        _('Code'),
        max_length=64,
        unique=True,
        help_text=_('Unique identifier for a product.'),
    )

    # Categorization
    _category = TreeForeignKey(
        Category,
        models.CASCADE,
        blank=True,
        null=True,
        verbose_name=_('Category'),
    )

    _brand = TreeForeignKey(
        Brand,
        models.CASCADE,
        blank=True,
        null=True,
        verbose_name=_('Brand'),
    )

    _manufacturer = TreeForeignKey(
        Manufacturer,
        models.CASCADE,
        blank=True,
        null=True,
        verbose_name=_('Manufacturer'),
    )

    # Pricing
    _unit_price = MoneyField(
        _('Unit price'),
        default=0,
        help_text=_("For variants leave empty to use the Group price."),
    )

    _discount = models.DecimalField(
        _('Discount %'),
        blank=True,
        null=True,
        max_digits=4,
        decimal_places=2,
        validators=[MinValueValidator(Decimal('0.00'))],
        help_text=_("For variants leave empty to use Group discount."),
    )

    _tax = models.ForeignKey(
        Tax,
        models.SET_NULL,
        blank=True,
        null=True,
        verbose_name=_('Tax'),
        help_text=_(
            "Tax to be applied to this product. Variants inherit tax percentage from their Group, and should "
            "leave this field empty."
        ),
    )

    # Settings
    kind = models.PositiveSmallIntegerField(
        _('Kind'),
        choices=KINDS,
        default=SINGLE,
        help_text=_(
            'Choose a product type. Single products are products without variations. Group products are base products '
            'that hold variants and their common info, they cannot be added to cart. Variants are variations of a '
            'product that must select a Group product, and set their unique set of attributes. '

shopit/templates/shopit/catalog/categorization_detail.html
{% extends "shopit/catalog/product_list.html" %}

{% block page_title %}{{ categorization }}{% endblock %}

shopit/templates/shopit/catalog/categorization_list.html
{% extends "shopit/base.html" %}
{% load i18n mptt_tags %}

{% block page_title %}{% trans "Categorization" %}{% endblock %}

{% block content %}
  <ul>
    {% recursetree categorization_list %}
      <li>
        <a href="{{ node.get_absolute_url }}">{{ node.name }}</a>
        {% if not node.is_leaf_node %}
          <ul>{{ children }}</ul>
        {% endif %}
      </li>
    {% endrecursetree %}
  </ul>
{% endblock %}

shopit/templates/shopit/catalog/product_detail.html
{% extends "shopit/base.html" %}
{% load i18n cms_tags sekizai_tags shop_tags shopit_tags %}

{% block page_title %}{{ product.name }}{% endblock %}

{% block content %}
  <div class="col-md-8 push-2">
    {{ product.description|safe }}
    <h4 id="price" class="text-info">{{ product.price }}</h4>
    <hr>

    {# Display attribute choices for a group product. #}
    {% if product.is_group %}
      <form id="attributes" class="mb-3">
        <h5>{% trans "Choose variation" %}</h5>
        {% for attr in product.get_attribute_choices.values %}
          <div class="row">
            <div class="form-group col-md-4">
              <label for="id_{{ attr.code }}">{{ attr.name }}</label>
              <select id="id_{{ attr.code }}" name="{{ attr.code }}">
                {% for option in attr.choices %}
                  <option value="{{ option.value }}">{{ option.name }}</option>
                {% endfor %}
              </select>
            </div>
          </div>
        {% endfor %}
      </form>

      <p id="variant" class="badge badge-default">{% trans "Not available." %}</p>
    {% endif %}

    {% add_to_cart watch=True %}

    <div>{% render_placeholder product.content %}</div>
  </div>

  {% addtoblock "js" %}
    <script>
      (function ($) {
        'use strict';

        var PRODUCT = $.parseJSON('{{ data|rest_json|escapejs }}');

        $(document).ready(function () {
          var $addToCart = $('.add-to-cart');
          var $attributes = $('#attributes');

          var selectVariant = function () {
            var formData = $attributes.serializeArray();
            var variantExists = false;

            $.each(PRODUCT.variants, function (key, variant) {
              var valid = true;

              $.each(formData, function (key, option) {
                if (variant.attributes[option.name.replace('-', '_')].value !== option.value) { valid = false; }
              });

              if (valid) {
                $addToCart.trigger('setProduct', [variant]);
                variantExists = true;

                // Populate DOM with variant data here.
                $('#variant').text(variant.name +' ('+ variant.price +')');
                $('#price').text(variant.price);
                return false;
              }
            });

            if (!variantExists) {
              $addToCart.trigger('setProduct', [PRODUCT]);
              $('#variant').text('{% trans "Not available." %}');
            }
          };

          if (PRODUCT.variants) {
            selectVariant();
            $attributes.find('select').on('change', selectVariant);
          } else {
            $addToCart.trigger('setProduct', [PRODUCT]);
          }
        });

      })(jQuery);
    </script>
  {% endaddtoblock %}
{% endblock %}

shopit/templates/shopit/catalog/product_list.html
{% extends "shopit/base.html" %}
{% load i18n shopit_tags %}

{% block page_title %}{% trans "Products" %}{% endblock %}

{% block content %}
  <div class="row">
    <div class="col-md-3">
      {# Filter by attributes #}
      {% get_attributes as attributes %}
      {% if attributes %}
        <div class="btn-group-vertical mb-3 w-100">
          <h5>{% trans "Attributes" %}</h5>
          {% for attr in attributes %}
            <div class="btn-group">
              <button class="btn btn-secondary dropdown-toggle text-left" data-toggle="dropdown">{{ attr }}</button>
              <div class="dropdown-menu">
                {% for choice in attr.get_choices %}
                  <a href="?{% query_transform attr.code choice.value %}" class="dropdown-item">{{ choice }}</a>
                {% endfor %}
              </div>
            </div>
          {% endfor %}
        </div>
      {% endif %}

      {# Filter by price #}
      {% get_price_steps 3 as price_steps %}
      {% if price_steps %}
        <h5>{% trans "Price from / price to" %}</h5>
        <div class="btn-group w-100 mb-3">
          <div class="btn-group w-50">
            <button class="btn btn-secondary dropdown-toggle w-100" data-toggle="dropdown">
              {% if request.GET.pf %}{{ request.GET.pf|moneyformat }}{% else %}{{ price_steps|first }}{% endif %}
            </button>
            <div class="dropdown-menu">
              {% for step in price_steps %}
                <a href="?{% query_transform 'pf' step.as_decimal %}" class="dropdown-item">{{ step }}</a>
              {% endfor %}
            </div>
          </div>

          <div class="btn-group w-50">
            <button class="btn btn-secondary dropdown-toggle w-100" data-toggle="dropdown">
              {% if request.GET.pt %}{{ request.GET.pt|moneyformat }}{% else %}{{ price_steps|last }}{% endif %}
            </button>
            <div class="dropdown-menu">
              {% for step in price_steps %}
                <a href="?{% query_transform 'pt' step.as_decimal %}" class="dropdown-item">{{ step }}</a>
              {% endfor %}
            </div>
          </div>
        </div>
      {% endif %}
    </div>

    <section class="col-md-9">
      <div class="card-group">
        {% for product in product_list %}
          <div class="card col-md-4">
            <div class="card-block">
              <h4 class="card-title">{{ product }}</h4>
              <p class="card-text">{{ product.caption|linebreaksbr }}</p>
              <a href="{{ product.get_absolute_url }}" class="btn btn-primary">{% trans "Details" %}</a>
            </div>
          </div>
        {% empty %}
          <p>{% trans "No products." %}</p>
        {% endfor %}
      </div>
    </section>
  </div>
{% endblock %}