shopit/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url
from django.utils.translation import ugettext_lazy as _
from django.views.generic import RedirectView

from shopit import views
from shopit.conf import app_settings


def get_urls(name, prefixed=app_settings.SINGLE_APPHOOK):  # noqa
    """
    Returns url patterns for the given module.
    Checks if urls are handled with single or multiple apphooks.
    """
    pk_regexp = r'(?P<pk>\d+)'
    slug_regexp = r'(?P<slug>[-_\w\d]+)'
    path_regexp = r'(?P<path>[-_/\w\d]+)'
    list_regexp = r'^$'
    detail_regexp = r'^%s/$' % slug_regexp

    if name == 'shop':
        cart_regexp = _(r'cart/$')
        cart_empty_regexp = _(r'cart/empty/$')
        watch_regexp = _(r'watch/$')
        checkout_regexp = _(r'checkout/$')
        thanks_regexp = _(r'thanks/$')

        if prefixed:
            list_regexp = _(r'shop/$')
            cart_regexp = _(r'shop/cart/$')
            cart_empty_regexp = _(r'shop/cart/empty/$')
            watch_regexp = _(r'shop/watch/$')
            checkout_regexp = _(r'shop/checkout/$')
            thanks_regexp = _(r'shop/thanks/$')

        return [
            url(list_regexp, RedirectView.as_view(pattern_name='shopit-cart')),
            url(cart_regexp, views.CartView.as_view(), name='shopit-cart'),
            url(cart_empty_regexp, views.CartView.as_view(empty=True), name='shopit-cart-empty'),
            url(watch_regexp, views.WatchView.as_view(), name='shopit-watch'),
            url(checkout_regexp, views.CheckoutView.as_view(), name='shopit-checkout'),
            url(thanks_regexp, views.ThanksView.as_view(), name='shopit-thanks'),
        ]

    if name == 'account':
        reset_confirm_kwargs = r'(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})'

        detail_regexp = list_regexp
        login_regexp = _(r'^login/$')
        logout_regexp = _(r'^logout/$')
        register_regexp = _(r'^register/$')
        reset_regexp = _(r'^reset/$')
        reset_confirm_regexp = _(r'^reset/confirm/%s/$') % reset_confirm_kwargs
        order_list_regexp = _(r'^orders/$')
        order_detail_regexp = _(r'^orders/%s/$') % pk_regexp
        order_latest_regexp = _(r'^orders/latest/$')
        settings_regexp = _(r'^settings/$')
        settings_details_regexp = _(r'^settings/details/$')
        settings_password_regexp = _(r'^settings/password/$')

        if prefixed:
            detail_regexp = _(r'^account/$')
            login_regexp = _(r'^account/login/$')
            logout_regexp = _(r'^account/logout/$')
            register_regexp = _(r'^account/register/$')
            reset_regexp = _(r'^account/reset/$')
            reset_confirm_regexp = _(r'^account/reset/confirm/%s/$') % reset_confirm_kwargs
            order_list_regexp = _(r'^account/orders/$')
            order_detail_regexp = _(r'^account/orders/%s/$') % pk_regexp
            order_latest_regexp = _(r'^account/orders/latest/$')
            settings_regexp = _(r'^account/settings/$')
            settings_details_regexp = _(r'^account/settings/details/$')
            settings_password_regexp = _(r'^account/settings/password/$')

        return [
            url(detail_regexp, views.AccountDetailView.as_view(), name='shopit-account-detail'),
            url(login_regexp, views.AccountLoginView.as_view(), name='shopit-account-login'),
            url(logout_regexp, views.AccountLogoutView.as_view(), name='shopit-account-logout'),
            url(register_regexp, views.AccountRegisterView.as_view(), name='shopit-account-register'),
            url(reset_regexp, views.AccountResetView.as_view(), name='shopit-account-reset'),
            url(reset_confirm_regexp, views.AccountResetConfirmView.as_view(), name='shopit-account-reset-confirm'),
            url(order_list_regexp, views.AccountOrderView.as_view(), name='shopit-account-order-list'),
            url(order_detail_regexp, views.AccountOrderView.as_view(many=False), name='shopit-account-order-detail'),
            url(order_latest_regexp, views.AccountOrderView.as_view(latest=True), name='shopit-account-order-latest'),
            url(settings_regexp, views.AccountSettingsView.as_view(), name='shopit-account-settings'),
            url(settings_details_regexp, views.AccountSettingsView.as_view(action='details'),
                name='shopit-account-settings-details'),
            url(settings_password_regexp, views.AccountSettingsView.as_view(action='password'),
                name='shopit-account-settings-password'),
        ]

    if name == 'categories':
        detail_regexp = r'^%s/$' % path_regexp

        if prefixed:
            list_regexp = _(r'^categories/$')
            detail_regexp = _(r'^categories/%s/$') % path_regexp

        return [
            url(list_regexp, views.CategoryListView.as_view(), name='shopit-category-list'),
            url(detail_regexp, views.CategoryDetailView.as_view(), name='shopit-category-detail'),
        ]

    if name == 'brands':
        detail_regexp = r'^%s/$' % path_regexp

        if prefixed:
            list_regexp = _(r'^brands/$')
            detail_regexp = _(r'^brands/%s/$') % path_regexp

        return [
            url(list_regexp, views.BrandListView.as_view(), name='shopit-brand-list'),
            url(detail_regexp, views.BrandDetailView.as_view(), name='shopit-brand-detail'),
        ]

    if name == 'manufacturers':
        detail_regexp = r'^%s/$' % path_regexp

        if prefixed:
            list_regexp = _(r'^manufacturers/$')
            detail_regexp = _(r'^manufacturers/%s/$') % path_regexp

        return [
            url(list_regexp, views.ManufacturerListView.as_view(), name='shopit-manufacturer-list'),
            url(detail_regexp, views.ManufacturerDetailView.as_view(), name='shopit-manufacturer-detail'),
        ]

    if name == 'products':
        review_regexp = _(r'^%s/reviews/$') % slug_regexp
        review_detail_regexp = _(r'^%s/reviews/%s/$') % (slug_regexp, pk_regexp)
        add_to_cart_regexp = _(r'^%s/add-to-cart/$') % slug_regexp

        if prefixed:
            list_regexp = _(r'^products/$')
            detail_regexp = _(r'^products/%s/$') % slug_regexp
            review_regexp = _(r'^products/%s/reviews/$') % slug_regexp
            review_detail_regexp = _(r'^products/%s/reviews/%s/$') % (slug_regexp, pk_regexp)
            add_to_cart_regexp = _(r'^products/%s/add-to-cart/$') % slug_regexp

        return [
            url(list_regexp, views.ProductListView.as_view(), name='shopit-product-list'),
            url(detail_regexp, views.ProductDetailView.as_view(), name='shopit-product-detail'),
            url(review_regexp, views.ProductReviewListView.as_view(), name='shopit-product-review-list'),
            url(review_detail_regexp, views.ProductReviewDetailView.as_view(), name='shopit-product-review-detail'),
            url(add_to_cart_regexp, views.AddToCartView.as_view(), name='shopit-add-to-cart'),
        ]


urlpatterns = []
for name in ('shop', 'account', 'categories', 'brands', 'manufacturers', 'products'):
    urlpatterns.extend(get_urls(name, prefixed=True))

shopit/models/order.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.core.urlresolvers import NoReverseMatch, reverse
from django.db import models
from django.utils import timezone
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext_lazy as _
from django_fsm import transition
from shop.models.order import BaseOrder, BaseOrderItem
from shop.models.order import OrderManager as OrderManagerBase


class OrderManager(OrderManagerBase):
    def get_summary_url(self):
        try:
            return reverse('shopit-account-order-list')
        except NoReverseMatch:
            return super(OrderManager, self).get_summary_url()

    def get_latest_url(self):
        try:
            return reverse('shopit-account-order-latest')
        except NoReverseMatch:
            return reverse('shopit-thanks')
        except NoReverseMatch:
            return super(OrderManager, self).get_latest_url()


@python_2_unicode_compatible
class Order(BaseOrder):
    number = models.PositiveIntegerField(
        _("Order Number"),
        null=True,
        default=None,
        unique=True,
    )

    shipping_address_text = models.TextField(
        _("Shipping Address"),
        blank=True,
        null=True,
        help_text=_('Shipping address at the moment of purchase.'),
    )

    billing_address_text = models.TextField(
        _("Billing Address"),
        blank=True,
        null=True,
        help_text=_('Billing address at the moment of purchase.'),
    )

    objects = OrderManager()

    class Meta:
        db_table = 'shopit_orders'
        verbose_name = _('Order')
        verbose_name_plural = _('Orders')

    def __str__(self):
        return self.get_number() if self.number else str(self.pk)

    def get_absolute_url(self):
        try:
            return reverse('shopit-account-order-detail', args=[self.pk])
        except NoReverseMatch:
            pass

    def get_or_assign_number(self):
        """
        Set a unique number to identify this Order object. The first 4 digits
        represent the current year. The last five digits represent a
        zero-padded incremental counter.
        """
        if self.number is None:
            epoch = timezone.now().date()
            epoch = epoch.replace(epoch.year, 1, 1)
            aggr = Order.objects.filter(number__isnull=False, created_at__gt=epoch).aggregate(models.Max('number'))
            try:
                epoc_number = int(str(aggr['number__max'])[4:]) + 1
                self.number = int('{0}{1:05d}'.format(epoch.year, epoc_number))
            except (KeyError, ValueError):
                # the first order this year
                self.number = int('{0}00001'.format(epoch.year))
        return self.get_number()

    def get_number(self):
        return str(self.number)[:4] + '-' + str(self.number)[4:]

    @classmethod
    def resolve_number(cls, number):
        number = number[:4] + number[5:]
        return dict(number=number)

    def populate_from_cart(self, cart, request):
        self.shipping_address_text = cart.shipping_address.as_text() if cart.shipping_address else ''
        self.billing_address_text = cart.billing_address.as_text() if cart.billing_address else ''

        # in case one of the addresses was None, the customer presumably intended the other one.
        if not self.shipping_address_text:
            self.shipping_address_text = self.billing_address_text
        if not self.billing_address_text:
            self.billing_address_text = self.shipping_address_text
        super(Order, self).populate_from_cart(cart, request)

        # After order was populated with cart data, delete discount codes.
        cart.delete_discount_codes()

    def is_fully_paid(self):
        return super(Order, self).is_fully_paid()

    @transition(field='status', source='*', target='payment_confirmed', conditions=[is_fully_paid],
                custom=dict(admin=False))
    def acknowledge_payment(self, by=None):
        """
        This is here only to force setting `admin=False` to hide the
        button in admin.
        """


@python_2_unicode_compatible
class OrderItem(BaseOrderItem):
    quantity = models.IntegerField(_('Ordered quantity'))

    canceled = models.BooleanField(
        _('Item canceled'),
        default=False,
    )

    class Meta:
        db_table = 'shopit_order_items'
        verbose_name = _('Order item')
        verbose_name_plural = _('Order items')

    def __str__(self):
        return self.product_name

    def populate_from_cart_item(self, cart_item, request):
        self.product_code = cart_item.product.product_code
        super(OrderItem, self).populate_from_cart_item(cart_item, request)

shopit/forms/account.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django import forms
from django.contrib.auth import authenticate, get_user_model, login, update_session_auth_hash
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm, UserCreationForm
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _

from shopit.conf import app_settings
from shopit.models.customer import Customer


class CleanEmailMixin(object):
    """
    Mixin used in forms where customers email is modified or created.
    Checks that email doesn't already exists.
    """
    def clean_email(self):
        email = self.cleaned_data['email']
        if 'email' in self.changed_data and get_user_model().objects.filter(is_active=True, email=email).exists():
            raise ValidationError(_('An account with this email address already exists.'))
        return email


class AccountLoginForm(AuthenticationForm):
    """
    Override username to be an email field, to disallow username logins.
    """
    username = forms.EmailField(label=_('Email address'))


class AccountRegisterForm(CleanEmailMixin, UserCreationForm):
    email = forms.EmailField(label=_('Email address'))

    class Meta:
        model = Customer
        fields = ['email', 'password1', 'password2']

    def __init__(self, *args, **kwargs):
        # Override default init from `UserCreationForm` to use email as
        # username field, and set autofocus.
        super(UserCreationForm, self).__init__(*args, **kwargs)
        self.fields['email'].widget.attrs.update({'autofocus': ''})

    def save(self, request, commit=False):
        self.instance = Customer.objects.get_from_request(request)
        self.instance.recognize_as_registered()
        self.instance.user.is_active = True
        self.instance.user.email = self.cleaned_data['email']
        password = self.cleaned_data['password1']
        self.instance.user.set_password(password)
        self.instance.save()
        user = authenticate(username=self.instance.user.username, password=password)
        login(request, user)
        return self.instance


class AccountDetailsForm(CleanEmailMixin, forms.ModelForm):
    first_name = forms.CharField(
        label=_('First name'),
        max_length=30,
        required=False,
    )

    last_name = forms.CharField(
        label=_('Last name'),
        max_length=30,
        required=False,
    )

    email = forms.EmailField(label=_('Email address'))

    class Meta:
        model = Customer
        fields = ['salutation', 'first_name', 'last_name', 'email', 'phone_number']
        custom_fields = ['first_name', 'last_name', 'email']

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request')
        self.instance = Customer.objects.get_from_request(self.request)
        kwargs['instance'] = self.instance
        kwargs['initial'] = dict([(x, getattr(self.instance, x)) for x in self.Meta.custom_fields])
        super(AccountDetailsForm, self).__init__(*args, **kwargs)
        self.fields['phone_number'].required = app_settings.PHONE_NUMBER_REQUIRED

    def save(self, commit=True):
        for field in self.Meta.custom_fields:
            setattr(self.instance, field, self.cleaned_data[field])
        customer = super(AccountDetailsForm, self).save(commit)
        return customer

    def get_success_message(self):
        return _('Info successfully updated.')  # pragma: no cover


class AccountPasswordForm(PasswordChangeForm):
    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request')
        super(AccountPasswordForm, self).__init__(self.request.user, *args, **kwargs)

    def save(self, commit=True):
        user = super(AccountPasswordForm, self).save(commit)
        update_session_auth_hash(self.request, user)
        return user

    def get_success_message(self):
        return _('Password successfully changed.')  # pragma: no cover

shopit/templates/shopit/account/account_detail.html
{% extends "shopit/base.html" %}
{% load i18n %}

{% block page_title %}{% trans "Account" %}{% endblock %}

{% block content %}
  <ul>
    <li><a href="{% url 'shopit-account-detail' %}">{% trans "Dashboard" %}</a></li>
    <li><a href="{% url 'shopit-account-order-list' %}">{% trans "Orders" %}</a></li>
    <li><a href="{% url 'shopit-account-settings' %}">{% trans "Settings" %}</a></li>
    <li><a href="{% url 'shopit-account-logout' %}">{% trans "Logout" %}</a></li>
  </ul>

  {% block body %}
    <p>{% trans "Welcome" %}, {{ customer.get_full_name }}.</p>
  {% endblock %}
{% endblock %}

shopit/templates/shopit/account/account_login.html
{% extends "shopit/base.html" %}
{% load i18n %}

{% block page_title %}{% trans "Account login" %}{% endblock %}

{% block content %}
  <form action="{% url 'shopit-account-login' %}" method="POST" data-ajax-success="{% url 'shopit-account-detail' %}" novalidate>
    {% csrf_token %}
    {{ form.as_p }}
    <p><a href="{% url 'shopit-account-reset' %}">{% trans "Forgot password?" %}</a></p>
    <button class="btn btn-primary">{% trans "Login" %}</button> {% trans "or" %}
    <a href="{% url 'shopit-account-register' %}" class="btn btn-secondary">{% trans "Register" %}</a>
  </form>
{% endblock %}

shopit/templates/shopit/account/account_order_detail.html
{% extends "shopit/account/account_detail.html" %}
{% load i18n shopit_tags %}

{% block page_title %}{{ block.super }} &bull; {% trans "Order" %} #{{ order }}{% endblock %}

{% block body %}
  {% order order %}
{% endblock %}

shopit/templates/shopit/account/account_order_list.html
{% extends "shopit/account/account_detail.html" %}
{% load i18n %}

{% block page_title %}{{ block.super }} &bull; {% trans "Orders" %}{% endblock %}

{% block body %}
  <ul>
    {% for order in order_list %}
      <li><a href="{{ order.get_absolute_url }}">{{ order }}</a></li>
    {% empty %}
      <li>{% trans "No orders." %}</li>
    {% endfor %}
  </ul>
{% endblock %}

shopit/templates/shopit/account/account_register.html
{% extends "shopit/base.html" %}
{% load i18n %}

{% block page_title %}{% trans "Account register" %}{% endblock %}

{% block content %}
  <form action="{% url 'shopit-account-register' %}" method="POST" data-ajax-success="{% url 'shopit-account-detail' %}" novalidate>
    {% csrf_token %}
    {{ form.as_p }}
    <button class="btn btn-primary">{% trans "Register" %}</button>
  </form>
{% endblock %}

shopit/templates/shopit/account/account_reset.html
{% extends "shopit/base.html" %}
{% load i18n %}

{% block page_title %}{% trans "Password reset" %}{% endblock %}

{% block content %}
  <form action="{% url 'shopit-account-reset' %}" method="POST" data-ajax-success="{% url 'shopit-account-login' %}" novalidate>
    {% csrf_token %}
    {{ form.as_p }}
    <button class="btn btn-primary">{% trans "Reset password" %}</button>
  </form>
{% endblock %}

shopit/templates/shopit/account/account_reset_confirm.html
{% extends "shopit/base.html" %}
{% load i18n %}

{% block page_title %}{% if validlink %}{% blocktrans %}New password for '{{ user_name }}'{% endblocktrans %}{% else %}{% trans "Link is invalid" %}{% endif %}{% endblock %}

{% block content %}
  {% if validlink %}
    <form action="{{ request.path }}" method="POST" data-ajax-success="{% url 'shopit-account-login' %}" novalidate>
      {% csrf_token %}
      {{ form.as_p }}
      <button class="btn btn-primary">{% trans "Reset password" %}</button>
    </form>
  {% else %}
    <p>{% trans "Please try again." %}</p>
  {% endif %}
{% endblock %}

shopit/templates/shopit/account/account_settings.html
{% extends "shopit/account/account_detail.html" %}
{% load i18n %}

{% block page_title %}{{ block.super }} &bull; {% trans "Settings" %}{% endblock %}

{% block body %}
  <ul>
    <li><a href="{% url 'shopit-account-settings-details' %}">{% trans "Update info" %}</a></li>
    <li><a href="{% url 'shopit-account-settings-password' %}">{% trans "Change password" %}</a></li>
  </ul>

  {% if action %}
    <form action="{% url 'shopit-account-settings-'|add:action %}" method="POST" data-ajax-success="{% url 'shopit-account-settings' %}" novalidate>
      {% csrf_token %}
      {{ form.as_p }}
      <button class="btn btn-primary">{% trans "Submit" %}</button>
    </form>
  {% endif %}
{% endblock %}